# Generated by Django 5.0.6 on 2024-06-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
